import PDFDocument from 'pdfkit';

const clamp = (value, max = 300) => String(value || '').trim().slice(0, max);

const bullets = (items, fallback = 'None captured for this session.') =>
  items.length ? items.map((item) => `• ${item}`).join('\n') : fallback;

const writeSection = (doc, title, body, opts = {}) => {
  doc
    .font('Helvetica-Bold')
    .fontSize(12)
    .fillColor('#0f172a')
    .text(title, { align: 'left' });

  doc.moveDown(0.25);
  doc
    .font('Helvetica')
    .fontSize(10.5)
    .fillColor('#1f2937')
    .text(body, {
      align: 'left',
      lineGap: 2,
      ...opts,
    });

  doc.moveDown(0.85);
};

export const buildClinicalReportPdfBuffer = async (report) => {
  const doc = new PDFDocument({
    size: 'A4',
    margin: 44,
    info: {
      Title: `AuraOS Clinical Report - ${report.userId || 'Unknown User'}`,
      Author: 'AuraOS Clinical Intelligence Layer',
    },
  });

  const chunks = [];
  doc.on('data', (chunk) => chunks.push(chunk));

  const worries = (report.shatteredWorryBlocks || [])
    .slice(0, 10)
    .map((w, i) => `${i + 1}. ${clamp(w.text, 90)} [${w.status || 'active'}]`);

  const timeline = (report.timelineMicroquests || [])
    .sort((a, b) => (a.order || 0) - (b.order || 0))
    .slice(0, 10)
    .map((q, i) => {
      const duration = Number(q.duration_minutes) || 2;
      const completeTag = q.completed ? 'completed' : 'pending';
      return `${i + 1}. ${clamp(q.action, 120)} (~${duration}m, ${completeTag})`;
    });

  const generatedAt = new Date(report.meta?.generatedAt || report.createdAt || Date.now())
    .toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' });

  doc
    .rect(36, 30, doc.page.width - 72, 46)
    .fill('#0f172a')
    .fillColor('#e2e8f0')
    .font('Helvetica-Bold')
    .fontSize(14)
    .text('AuraOS Clinical Triage Report', 48, 44, { align: 'left' })
    .font('Helvetica')
    .fontSize(9.5)
    .text(`Generated: ${generatedAt}`, 48, 61, { align: 'left' });

  doc.fillColor('#111827');
  doc.moveDown(2);

  writeSection(
    doc,
    'Session Context',
    [
      `User ID: ${clamp(report.userId, 80) || 'N/A'}`,
      `Current task: ${clamp(report.currentTask, 180) || 'N/A'}`,
      `Selected blocker: ${clamp(report.selectedBlocker, 120) || 'N/A'}`,
      `Vocal arousal: ${Number(report.vocalArousalScore || 0).toFixed(1)}/10`,
      `Risk level: ${clamp(report.riskLevel, 40) || 'watch'}`,
    ].join('\n')
  );

  writeSection(
    doc,
    'Initial Anxiety Query',
    clamp(report.initialAnxietyQuery, 600) || 'No direct anxiety query was captured in this report window.'
  );

  writeSection(doc, 'Shattered Worry Blocks', bullets(worries));
  writeSection(doc, 'Shattered Tasks Timeline (User Order)', bullets(timeline));

  writeSection(
    doc,
    'AI Stress Summary',
    clamp(report.aiStressSummary, 1200) || 'AI summary unavailable for this session.'
  );

  const guardianLine = report.guardian
    ? `${clamp(report.guardian.name, 80) || 'Guardian'} | ${clamp(report.guardian.relation, 60) || 'relation N/A'}`
    : 'Guardian details unavailable';
  const contactLine = report.guardian
    ? `${clamp(report.guardian.phone, 30) || 'phone N/A'} | ${clamp(report.guardian.email, 120) || 'email N/A'}`
    : 'No contact details';

  writeSection(doc, 'Guardian Contact', `${guardianLine}\n${contactLine}`);

  doc
    .font('Helvetica')
    .fontSize(8.5)
    .fillColor('#6b7280')
    .text(
      'This report is generated by AuraOS to support informed caregiving during stress spikes. It is not a medical diagnosis.',
      { align: 'left' }
    );

  doc.end();

  return new Promise((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
};

