import twilio from 'twilio';

let _client = null;

const getClient = () => {
  if (_client) return _client;

  const sid = process.env.TWILIO_ACCOUNT_SID;
  const token = process.env.TWILIO_AUTH_TOKEN;

  if (!sid || !token) return null;

  _client = twilio(sid, token);
  return _client;
};

const normalizeChannel = (channel) => {
  const value = String(channel || 'whatsapp').trim().toLowerCase();
  if (value === 'sms' || value === 'whatsapp' || value === 'none') return value;
  if (value === 'email') return 'none';
  return 'whatsapp';
};

const normalizePhone = (phone) => {
  if (!phone) return '';

  let cleaned = String(phone).trim().replace(/\s+/g, '');
  cleaned = cleaned.replace(/^whatsapp:/i, '');

  if (!cleaned) return '';
  if (!cleaned.startsWith('+')) cleaned = `+${cleaned}`;

  return cleaned;
};

const safeBrief = (brief = {}) => ({
  risk_level: brief.risk_level || 'watch',
  observed_pattern: brief.observed_pattern || 'Elevated stress pattern was detected.',
  analogy: brief.analogy || 'Like too many browser tabs open at once.',
  vocal_analysis: brief.vocal_analysis || 'Vocal stress markers indicate elevated strain.',
  aura_action_taken: brief.aura_action_taken || 'A supportive decompression intervention was deployed.',
  parent_action: brief.parent_action || 'Offer reassurance, hydration, and a short break before resuming tasks.',
});

const formatWhatsAppMessage = (rawBrief, userName) => {
  const brief = safeBrief(rawBrief);
  const riskEmoji = {
    watch: 'YELLOW',
    'pre-burnout': 'ORANGE',
    'acute-distress': 'RED',
  }[brief.risk_level] || 'YELLOW';

  return [
    '*AURA CLINICAL ADVISORY*',
    `*Patient:* ${userName || 'Your child'} | *${new Date().toLocaleString('en-IN', { dateStyle: 'short', timeStyle: 'short' })}*`,
    `*Risk Level:* ${riskEmoji} ${brief.risk_level.replace('-', ' ').toUpperCase()}`,
    '',
    '*Detection*',
    brief.observed_pattern,
    '',
    '*Analogy*',
    `_${brief.analogy}_`,
    '',
    '*Vocal Analysis*',
    brief.vocal_analysis,
    '',
    '*Aura Action Taken*',
    brief.aura_action_taken,
    '',
    '*Your Action Right Now*',
    brief.parent_action,
    '',
    '_Generated by AuraOS Clinical Triage. Do not share patient data externally._',
  ].join('\n');
};

const formatSmsMessage = (rawBrief, userName) => {
  const brief = safeBrief(rawBrief);

  return [
    `AURA ALERT [${brief.risk_level.toUpperCase()}]`,
    `Patient: ${userName || 'your child'}`,
    `Pattern: ${brief.observed_pattern.slice(0, 120)}`,
    `Action: ${brief.parent_action.slice(0, 200)}`,
    'Sent by AuraOS.',
  ].join(' | ');
};

/**
 * Sends a Guardian Triage Brief to the configured channel.
 * Returns { success, channel, sid, mock, skipped, error } and never throws.
 */
export const sendGuardianAlert = async ({ brief, userName, guardianPhone, channel = 'whatsapp', mediaUrl = null }) => {
  const selectedChannel = normalizeChannel(channel);
  const normalizedPhone = normalizePhone(guardianPhone);
  const client = getClient();

  if (selectedChannel === 'none') {
    return { success: true, channel: 'none', mock: true, skipped: true };
  }

  if (!normalizedPhone) {
    console.warn('[Twilio] Missing guardian phone; using mock delivery.');
    console.log('[MOCK BRIEF]\n', formatWhatsAppMessage(brief, userName));
    return { success: true, channel: 'mock', mock: true };
  }

  if (!client) {
    console.log('[Twilio MOCK] Would send to:', normalizedPhone);
    console.log('[MOCK BRIEF]\n', formatWhatsAppMessage(brief, userName));
    return { success: true, channel: 'mock', mock: true };
  }

  try {
    let message;

    if (selectedChannel === 'whatsapp') {
      const fromWhatsApp = (process.env.TWILIO_WHATSAPP_FROM || 'whatsapp:+14155238886').startsWith('whatsapp:')
        ? (process.env.TWILIO_WHATSAPP_FROM || 'whatsapp:+14155238886')
        : `whatsapp:${process.env.TWILIO_WHATSAPP_FROM}`;

      const payload = {
        from: fromWhatsApp,
        to: `whatsapp:${normalizedPhone}`,
        body: formatWhatsAppMessage(brief, userName),
      };
      if (mediaUrl) payload.mediaUrl = [mediaUrl];

      message = await client.messages.create(payload);
    } else {
      const smsFromRaw = process.env.TWILIO_SMS_FROM
        || (process.env.TWILIO_WHATSAPP_FROM || '').replace(/^whatsapp:/i, '')
        || '+10000000000';

      message = await client.messages.create({
        from: smsFromRaw,
        to: normalizedPhone,
        body: formatSmsMessage(brief, userName),
      });
    }

    console.log(`[Twilio] Alert sent via ${selectedChannel}. SID: ${message.sid}`);
    return { success: true, channel: selectedChannel, sid: message.sid, mock: false };
  } catch (err) {
    console.error('[Twilio] Send failed:', err.message);
    return { success: false, channel: selectedChannel, error: err.message, mock: false };
  }
};
